
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kulslhqhkwvdchkaphxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bHNsaHFoa3d2ZGNoa2FwaHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTc0OTgsImV4cCI6MjA1OTA3MzQ5OH0.4K_9ILOFV4PbuzL8ZJENmAF9Gvo8-FNHp2PLq8vkXNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
